import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { SongSlide } from "@/vmusic/ControlRoom/utils/lyricsParser";

interface SongSlidesState {
  slides: SongSlide[];
  currentSlideId: string | null;
  songTitle: string;
  isAutoGeneratedTitle: boolean; // true = auto-generated from paste, false = saved title
  currentSongId: string | null; // ID of the currently loaded song (null if pasted)
  isSaving: boolean;
}

const initialState: SongSlidesState = {
  slides: [],
  currentSlideId: null,
  songTitle: "",
  isAutoGeneratedTitle: true,
  currentSongId: null,
  isSaving: false,
};

const songSlidesSlice = createSlice({
  name: "songSlides",
  initialState,
  reducers: {
    setSlides: (state, action: PayloadAction<SongSlide[]>) => {
      state.slides = action.payload;
      // Auto-select first slide if slides exist
      if (action.payload.length > 0 && !state.currentSlideId) {
        state.currentSlideId = action.payload[0].id;
      }
      // Auto-generate title from first few words when new slides are pasted
      if (action.payload.length > 0) {
        const firstSlideContent = action.payload[0].content.trim();
        const firstWords = firstSlideContent.split(/\s+/).slice(0, 5).join(" ");
        state.songTitle =
          firstWords.length > 30
            ? firstWords.substring(0, 30) + "..."
            : firstWords;
        state.isAutoGeneratedTitle = true; // Mark as auto-generated
      }
      // Clear currentSongId when new slides are set (will be set by setCurrentSongId if loading)
      state.currentSongId = null;
    },
    setSongTitle: (state, action: PayloadAction<string>) => {
      state.songTitle = action.payload;
      state.isAutoGeneratedTitle = false; // Mark as saved/loaded title
    },
    setCurrentSongId: (state, action: PayloadAction<string | null>) => {
      state.currentSongId = action.payload;
    },
    setCurrentSlide: (state, action: PayloadAction<string>) => {
      state.currentSlideId = action.payload;
    },
    setIsSaving: (state, action: PayloadAction<boolean>) => {
      state.isSaving = action.payload;
    },
    clearSlides: (state) => {
      state.slides = [];
      state.currentSlideId = null;
      state.songTitle = "";
      state.isAutoGeneratedTitle = true;
      state.currentSongId = null;
    },
    addSlide: (state, action: PayloadAction<SongSlide>) => {
      state.slides.push(action.payload);
    },
    updateSlide: (
      state,
      action: PayloadAction<{ id: string; content: string }>
    ) => {
      const slide = state.slides.find((s) => s.id === action.payload.id);
      if (slide) {
        slide.content = action.payload.content;
      }
    },
    removeSlide: (state, action: PayloadAction<string>) => {
      state.slides = state.slides.filter((s) => s.id !== action.payload);
      // If removed slide was current, select first available
      if (state.currentSlideId === action.payload && state.slides.length > 0) {
        state.currentSlideId = state.slides[0].id;
      }
    },
    reorderSlides: (
      state,
      action: PayloadAction<{ fromIndex: number; toIndex: number }>
    ) => {
      const { fromIndex, toIndex } = action.payload;

      // Validate indices
      if (
        fromIndex < 0 ||
        fromIndex >= state.slides.length ||
        toIndex < 0 ||
        toIndex >= state.slides.length
      ) {
        return;
      }

      // Create a new array and move the slide
      const newSlides = [...state.slides];
      const [movedSlide] = newSlides.splice(fromIndex, 1);
      newSlides.splice(toIndex, 0, movedSlide);

      // Renumber slides by type
      // Chorus labels stay as "Chorus" but verses get renumbered
      const renumberedSlides = newSlides.map((slide, index) => {
        // Count how many slides of the same type come before this one
        const sameTypeBefore = newSlides
          .slice(0, index)
          .filter((s) => s.type === slide.type).length;

        const newNumber = sameTypeBefore + 1;

        // Format label based on type
        let newLabel: string;
        if (slide.type === "chorus") {
          // Chorus stays as just "Chorus" (no number for single chorus)
          // Or "Chorus 2" if multiple choruses exist
          const totalSameType = newSlides.filter(
            (s) => s.type === slide.type
          ).length;
          newLabel = totalSameType === 1 ? "Chorus" : `Chorus ${newNumber}`;
        } else {
          // Other types always show number
          newLabel = `${
            slide.type.charAt(0).toUpperCase() + slide.type.slice(1)
          } ${newNumber}`;
        }

        return {
          ...slide,
          number: newNumber,
          label: newLabel,
        };
      });

      state.slides = renumberedSlides;
    },
  },
});

export const {
  setSlides,
  setCurrentSlide,
  setSongTitle,
  setCurrentSongId,
  setIsSaving,
  clearSlides,
  addSlide,
  updateSlide,
  removeSlide,
  reorderSlides,
} = songSlidesSlice.actions;

export default songSlidesSlice.reducer;
