import { useState, useEffect } from "react";
import {
  ArrowLeftFromLine,
  GalleryHorizontal,
  GalleryThumbnails,
  Group,
  Minus,
  Square,
  SwitchCamera,
  User2Icon,
  X,
  MoreHorizontal,
  Settings,
  FileText,
} from "lucide-react";
import { HomeFilled } from "@ant-design/icons";
import { Switch } from "antd";
import { useAppSelector, useAppDispatch } from "@/store";
import {
  setCurrentScreen,
  setTheme,
  minimizeApp,
  maximizeApp,
  closeApp,
} from "@/store/slices/appSlice";
import { ThemeToggle } from "./ThemeToggler";
import { current } from "@reduxjs/toolkit";
import { useTheme } from "@/Provider/Theme";

const TitleBar = () => {
  const [isHovered, setIsHovered] = useState<string | null>(null);
  const [showDropdown, setShowDropdown] = useState<boolean>(false);

  const dispatch = useAppDispatch();
  const currentScreen = useAppSelector((state) => state.app.currentScreen);
  const theme = useAppSelector((state) => state.app.theme);
  const songTitle = useAppSelector((state) => state.songSlides.songTitle);
  const isAutoGeneratedTitle = useAppSelector(
    (state) => state.songSlides.isAutoGeneratedTitle
  );
  const currentSlideId = useAppSelector(
    (state) => state.songSlides.currentSlideId
  );
  const slides = useAppSelector((state) => state.songSlides.slides);
  const { isDarkMode, toggleDarkMode } = useTheme();

  // Get current slide info
  const currentSlide = slides.find((slide) => slide.id === currentSlideId);

  // Generate display title: only show if it's a saved/loaded title (not auto-generated)
  const getDisplayTitle = () => {
    // Only show title if it's from a saved/loaded song
    if (!isAutoGeneratedTitle && songTitle && songTitle.trim() !== "") {
      return songTitle;
    }

    return null;
  };

  const displayTitle = getDisplayTitle();

  // Hide title bar for presentation screens
  const shouldHideTitleBar = window.location.hash.includes(
    "presentation-display"
  );

  // Don't render title bar if it should be hidden
  if (shouldHideTitleBar) {
    return null;
  }

  useEffect(() => {
    const savedTheme = localStorage.getItem("bmusictheme");
    if (savedTheme) {
      dispatch(setTheme(savedTheme as any));
    }
  }, [dispatch]);

  // function to set theme choice for songs app
  const setThemeChoice = () => {
    const currentSongTheme = localStorage.getItem("bmusictheme") || "white";
    const newTheme = currentSongTheme === "creamy" ? "white" : "creamy";

    // Update localStorage
    localStorage.setItem("bmusictheme", newTheme);

    // Dispatch custom event to notify other components of the change
    window.dispatchEvent(
      new CustomEvent("localStorageChange", {
        detail: { key: "bmusictheme", newValue: newTheme },
      })
    );
  };

  const randombgs = `rgba(${Math.floor(Math.random() * 255)},${Math.floor(
    Math.random() * 255
  )},${Math.floor(Math.random() * 255)},0.6)`;

  const handleMinimize = () => {
    dispatch(minimizeApp());
  };

  const handleMaximize = () => {
    dispatch(maximizeApp());
  };

  const handleClose = () => {
    dispatch(closeApp());
  };
  const toggleDropdown = () => {
    setShowDropdown(!showDropdown);
  };

  const handleAddToPrelist = () => {
    // TODO: Implement add to prelist functionality
    console.log("Add to prelist clicked");
  };

  const selectedBg = isDarkMode ? "url('./wood10.jpg')" : "url(./wood10.jpg)";

  return (
    <div
      className="h-6 w-full fixed flex z-50 top-0 m-auto select-none"
      style={
        {
          WebkitAppRegion: "drag",
          backgroundImage: !isDarkMode
            ? `linear-gradient(to bottom,
             rgba(255, 255, 255, 0%) 0%,
             rgba(160, 160, 160, 1) 100%),
             ${selectedBg}`
            : `linear-gradient(to bottom,
             rgba(44, 44, 44, 0) 0%,
             #1c1c1c 80%),
              ${selectedBg}`,
          backgroundRepeat: "repeat",
          backgroundSize: !isDarkMode ? "30px" : "20px",
          backdropFilter: "blur(10px)",
          zIndex: 10,
        } as any
      }
    >
      <div className="flex w-full items-center justify-center px-2">
        {/* Control buttons excluded from dragging */}
        <div
          className="flex items-center justify-between w-full m-auto space-x-2"
          style={{ WebkitAppRegion: "no-drag" } as any} // Exclude control buttons from dragging
        >
          <div className="flex items-center justify-center gap-2">
            <div
              onClick={handleClose}
              onMouseEnter={() => setIsHovered("close")}
              onMouseLeave={() => setIsHovered(null)}
              className="w-4 h-4 rounded-full bg-[#FF5F57] hover:bg-red-600 hover:cursor-pointer flex items-center justify-center"
            >
              {isHovered === "close" && (
                <X className="text-white z-20 size-6" />
              )}
            </div>
            <div
              onClick={handleMinimize}
              onMouseEnter={() => setIsHovered("minimize")}
              onMouseLeave={() => setIsHovered(null)}
              className="w-4 h-4 text-white rounded-full bg-[#FFBD2E] hover:bg-yellow-600 hover:cursor-pointer flex items-center justify-center hover:text-white"
            >
              {isHovered === "minimize" && (
                <Minus className="text-white z-20 size-6" />
              )}
            </div>
            <div
              onClick={handleMaximize}
              onMouseEnter={() => setIsHovered("maximize")}
              onMouseLeave={() => setIsHovered(null)}
              className="w-4 h-4 rounded-full bg-[#28CA41] hover:bg-green-600 hover:cursor-pointer flex items-center justify-center"
            >
              {isHovered === "maximize" && (
                <Square className="text-white z-20 size-3" />
              )}
            </div>
            <div className="flex items-center justify-center gap-2">
              <div
                onClick={() => dispatch(setCurrentScreen("Home"))}
                className={`w-6 h-6 rounded-full flex items-center justify-center group cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800
                 ${currentScreen === "Songs" ? "bg-primary/20" : "hidden"}
                `}
              >
                <HomeFilled className="w-4 h-4 text-app-text group-hover:text-black dark:group-hover:text-white" />
              </div>
              {/* <div
                onClick={setThemeChoice}
                className={`w-6 h-6 rounded-full flex items-center justify-center group cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 ${
                  currentScreen === "Songs" ? "flex" : "hidden"
                }`}
                title="Mild theme 🟤"
              >
                <SwitchCamera className="w-4 h-4 text-app-text group-hover:text-black dark:group-hover:text-white" />
              </div> */}
              {/* <div
                onClick={() => dispatch(setCurrentScreen("backgrounds"))}
                className={`w-6 h-6 rounded-full flex items-center justify-center group cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 relative ${
                  currentScreen === "backgrounds" ? "bg-primary/10" : ""
                }`}
                title="Presentation backgrounds"
              >
                <GalleryHorizontal className="w-4 h-4 text-app-text group-hover:text-black dark:group-hover:text-white" />
                {currentScreen === "backgrounds" && (
                  <div className="absolute -bottom-2 w-1 h-1 rounded-full bg-primary"></div>
                )}
              </div> */}
              <div
                onClick={() => dispatch(setCurrentScreen("userguide"))}
                className={`w-6 h-6 rounded-full flex items-center justify-center group cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 relative ${
                  currentScreen !== "Songs" && "hidden"
                } ${currentScreen === "userguide" ? "bg-primary/10" : ""}`}
                title="User manual"
              >
                <User2Icon className="w-4 h-4 text-app-text group-hover:text-black dark:group-hover:text-white" />
                {currentScreen === "userguide" && (
                  <div className="absolute -bottom-2 w-1 h-1 rounded-full bg-primary"></div>
                )}
              </div>
              <ThemeToggle />
              {/* Song Title and Current Slide Display */}
              {currentScreen === "Songs" && (displayTitle || currentSlide) && (
                <div className="flex items-center gap-2">
                  {displayTitle && (
                    <div className="flex items-center gap-2 px-3 py-1 bg-app-surface/50 rounded-full border border-app-border/30 backdrop-blur-sm">
                      <FileText className="w-3 h-3 text-app-text-muted" />
                      <span className="text-sm font-medium text-app-text max-w-[200px] truncate">
                        {displayTitle}
                      </span>
                    </div>
                  )}
                  {currentSlide && (
                    <div className="flex items-center gap-1.5 px-2.5 py-1 bg-app-accent/20 rounded-full border border-app-accent/30 backdrop-blur-sm">
                      <span className="text-xs font-bold text-white ">
                        {currentSlide.label}
                      </span>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>

          <img
            src="./evsongsicon.png"
            alt="Description"
            className="w-4 h-4 animate-bounce"
          />
        </div>
      </div>
    </div>
  );
};

export default TitleBar;
